export const data = [
  {
    q1: '23%',
    q2: '34%',
    q3: '67%',
    category: "Пол",
    subcategory: "мужской",
    product: "Балтика 9",
  },
  {
    q1: '34%',
    q2: '45%',
    q3: '23%',
    category: "Пол",
    subcategory: "мужской",
    product: "охота крепкое",
  },
  {
    q1: '51%',
    q2: '23%',
    q3: '56%',
    category: "Пол",
    subcategory: "женский",
    product: "Балтика 9",
  },
  {
    q1: '45%',
    q2: '51%',
    q3: '23%',
    category: "Пол",
    subcategory: "женский",
    product: "охота крепкое",
  },
  {
    q1: '78%',
    q2: '34%',
    q3: '45%',
    category: "Возраст",
    subcategory: "24",
    product: "Балтика 9",
  },
  {
    q1: '34%',
    q2: '23%',
    q3: '11%',
    category: "Возраст",
    subcategory: "24",
    product: "охота крепкое",
  },
  {
    q1: '67%',
    q2: '34%',
    q3:'78%',
    category: "Возраст",
    subcategory: "35",
    product: "Балтика 9",
  },
  {
    q1: '34%',
    q2: '78%',
    q3: '11%',
    category: "Возраст",
    subcategory: "35",
    product: "охота крепкое",
  },
  {
    q1:'34%',
    q2: '11%',
    q3: '34%',
    category: "Наличие детей",
    subcategory: "нет",
    product: "Балтика 9",
  },
  {
    q1: '11%',
    q2: '34%',
    q3: '26%',
    category: "Наличие детей",
    subcategory: "нет",
    product: "охота крепкое",
  },
  {
    q1: '34%',
    q2: '11%',
    q3: '26%',
    category: "Наличие детей",
    subcategory: "2 детей",
    product: "Балтика 9",
  },
  {
    q1: '11%',
    q2: '26%',
    q3: '84%',
    category: "Наличие детей",
    subcategory: "2 детей",
    product: "охота крепкое",
  },

]