export const attributeMocks = [
  "AB InBev Efes",
  "AFB",
  "Bottle",
  "Can",
  "Craft",
  "Diageo",
  "DIOT",
  "Draught",
  "DTG",
  "ECONOMY",
  "Eichbaum",
  "Feldschlosschen Getranke AG",
  "Fruity & Sweet",
  "Import",
  "IMPORTED",
  "International Lagers PET",
  "International Lagers Single Serve",
  "Konix Brewery / Пензенская обл.",
  "LICENSED",
  "MAINSTREAM",
  "NA",
  "Oetker Group",
  "Packed",
  "PET",
  "PREMIUM",
  "RUSSIAN - FEDERAL",
  "RUSSIAN - REGIONAL",
  "Russian Lagers PET",
  "Russian Lagers Single Serve",
  "Specialty",
  "Strong",
  "SUPER PREMIUM",
  "Total",
  "Volfas Engelman",
  "X5 Retail Group",
  "Афанасий / Тверская обл.",
  "Бавария ГК / Владикавказ",
  "Бристоль",
  "Букет Чувашии",
  "Красное&Белое",
  "Лидское пиво / Беларусь",
  "Липецкпиво",
  "Лысковский пив.з-д г. Н.Новгород",
  "Магнит",
  "Майкопское пиво ООО",
  "Московская пивоваренная компания ЗАО",
  "Оазис ООО / Уфа",
  "Объединенные Пивоварни-Холдинг",
  "Очаково",
  "Пивоваренная компания Балтика",
  "Русская традиция ГК",
  "Татспиртпром",
  "Трехсосенский завод"
]