export const data = [
  {
    id: 1,
    startDate: "20 июня 2024",
    lastName: "Doe",
    reportName: "Отчет для пурины",
    link: 'https://romir.ru/media_data',
    postcode: '222-222',
    email: "john@example.com",
  },
  {
    id: 2,
    startDate: "15 мая 2023",
    lastName: "Smith",
    reportName: "Отчет для квартала",
    link: 'https://example.com/report',
    postcode: '123-456',
    email: "smith@example.com",
  },
  {
    id: 3,
    startDate: "10 апреля 2025",
    lastName: "Johnson",
    reportName: "Ежемесячный отчет",
    link: 'https://company.com/reports',
    postcode: '987-654',
    email: "johnson@example.com",
  },
  {
    id: 4,
    startDate: "5 июля 2023",
    lastName: "Brown",
    reportName: "Отчет по продажам",
    link: 'https://salesreport.com',
    postcode: '111-222',
    email: "brown@example.com",
  },
  {
    id: 5,
    startDate: "30 сентября 2024",
    lastName: "Williams",
    reportName: "Годовой отчет",
    link: 'https://annualreport.com',
    postcode: '333-444',
    email: "williams@example.com",
  },
  {
    id: 6,
    startDate: "12 декабря 2023",
    lastName: "Jones",
    reportName: "Отчет по производству",
    link: 'https://productionreport.com',
    postcode: '555-666',
    email: "jones@example.com",
  },
  {
    id: 7,
    startDate: "8 августа 2025",
    lastName: "Taylor",
    reportName: "Отчет по маркетингу",
    link: 'https://marketingreport.com',
    postcode: '777-888',
    email: "taylor@example.com",
  },
  {
    id: 8,
    startDate: "25 октября 2023",
    lastName: "Martinez",
    reportName: "Еженедельный отчет",
    link: 'https://weeklyreport.com',
    postcode: '999-000',
    email: "martinez@example.com",
  },
  {
    id: 9,
    startDate: "17 ноября 2024",
    lastName: "Garcia",
    reportName: "Отчет о финансах",
    link: 'https://financialreport.com',
    postcode: '123-789',
    email: "garcia@example.com",
  },
  {
    id: 10,
    startDate: "3 марта 2025",
    lastName: "Rodriguez",
    reportName: "Квартальный отчет по клиентам",
    link: 'https://clientreport.com',
    postcode: '456-789',
    email: "rodriguez@example.com",
  }
];

// правки по отправке
